import Link from 'next/link'
import { requireAdmin } from '@/lib/admin-auth'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
const statuses = ['new', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'returned']
export default async function OrdersPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  await requireAdmin(); const params = await searchParams; const page = Math.max(1, Number(params.page) || 1); const q = params.q?.trim() || ''; const status = statuses.includes(params.status || '') ? params.status : ''
  const { data, error } = await getSupabaseAdmin().from('orders').select('id,order_number,quantity,total_amount,status,created_at,wilaya,customers(full_name,phone)').order('created_at', { ascending: false })
  const all = (data ?? []).filter(o => { const customer = (Array.isArray(o.customers) ? o.customers[0] : o.customers) as unknown as { full_name?: string; phone?: string } | null; return (!status || o.status === status) && (!q || o.order_number.toLowerCase().includes(q.toLowerCase()) || String(customer?.full_name || '').toLowerCase().includes(q.toLowerCase()) || String(customer?.phone || '').includes(q)) }); const size = 20; const rows = all.slice((page - 1) * size, page * size)
  return <main className="admin-content" dir="ltr"><section className="admin-panel"><h2>Orders</h2><form className="admin-toolbar"><input className="admin-input" name="q" placeholder="Search order, customer, phone" defaultValue={q} /><select className="admin-select" name="status" defaultValue={status}><option value="">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</select><button className="admin-button">Filter</button></form>{error ? <div className="admin-error">Unable to load orders.</div> : rows.length === 0 ? <div className="admin-empty">No orders found.</div> : <><table className="admin-table"><thead><tr><th>Order number</th><th>Customer</th><th>Phone</th><th>Wilaya</th><th>Qty</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.map(o => { const customer = (Array.isArray(o.customers) ? o.customers[0] : o.customers) as unknown as { full_name: string; phone: string } | null; return <tr key={o.id}><td><Link href={`/admin/orders/${o.id}`}>{o.order_number}</Link></td><td>{customer?.full_name}</td><td>{customer?.phone}</td><td>{o.wilaya}</td><td>{o.quantity}</td><td>{Number(o.total_amount).toLocaleString()} DZD</td><td><span className="admin-status">{o.status}</span></td><td>{new Date(o.created_at).toLocaleDateString()}</td></tr> })}</tbody></table><p>{all.length} result(s) · page {page}</p></>}</section></main>
}
