import Link from 'next/link'
import { requireAdmin } from '@/lib/admin-auth'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
const statuses = ['new', 'confirmed', 'shipped', 'delivered', 'cancelled', 'returned'] as const
export default async function AdminDashboard() {
  await requireAdmin(); const { data: orders, error } = await getSupabaseAdmin().from('orders').select('id,order_number,total_amount,status,created_at,customers(full_name)').order('created_at', { ascending: false }); const rows = orders ?? []; const count = (s: string) => rows.filter(o => o.status === s).length; const revenue = rows.filter(o => !['cancelled', 'returned'].includes(o.status)).reduce((sum, o) => sum + Number(o.total_amount), 0)
  return <main className="admin-content" dir="ltr"><div className="admin-grid"><Metric label="Total orders" value={rows.length} />{statuses.map(s => <Metric key={s} label={s} value={count(s)} />)}<Metric label="Total revenue" value={`${revenue.toLocaleString()} DZD`} /></div><section className="admin-panel"><h2>Latest orders</h2>{error ? <div className="admin-error">Unable to load orders.</div> : rows.length === 0 ? <div className="admin-empty">No orders yet.</div> : <table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.slice(0, 10).map(o => { const customer = (Array.isArray(o.customers) ? o.customers[0] : o.customers) as unknown as { full_name: string } | null; return <tr key={o.id}><td><Link href={`/admin/orders/${o.id}`}>{o.order_number}</Link></td><td>{customer?.full_name ?? '—'}</td><td>{Number(o.total_amount).toLocaleString()} DZD</td><td><span className="admin-status">{o.status}</span></td><td>{new Date(o.created_at).toLocaleString()}</td></tr> })}</tbody></table>}</section></main>
}
function Metric({ label, value }: { label: string; value: number | string }) { return <div className="admin-card"><small>{label}</small><strong>{value}</strong></div> }
