'use client'
import { FormEvent, useEffect, useState } from 'react'
type Settings = { zrBaseUrl: string; zrTenantId: string; zrApiKey: string; metaPixelId: string; metaAccessToken: string; zrConfigured: boolean; metaConfigured: boolean }
const initial: Settings = { zrBaseUrl: '', zrTenantId: '', zrApiKey: '', metaPixelId: '', metaAccessToken: '', zrConfigured: false, metaConfigured: false }
export function IntegrationSettingsForm() {
  const [settings, setSettings] = useState(initial); const [message, setMessage] = useState(''); const [busy, setBusy] = useState('')
  useEffect(() => { fetch('/api/admin/integrations').then(r => r.json()).then(d => d.settings && setSettings(d.settings)).catch(() => setMessage('Unable to load settings.')) }, [])
  function update(key: keyof Settings, value: string) { setSettings(s => ({ ...s, [key]: value })) }
  async function save(event: FormEvent) { event.preventDefault(); setBusy('save'); const r = await fetch('/api/admin/integrations', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(settings) }); const d = await r.json(); if (d.settings) setSettings(d.settings); setMessage(r.ok ? 'Settings saved.' : 'Unable to save settings.'); setBusy('') }
  async function test(provider: 'zr' | 'meta') { setBusy(provider); const r = await fetch('/api/admin/integrations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ provider }) }); const d = await r.json(); setMessage(`${provider === 'zr' ? 'ZR Express' : 'Meta'}: ${String(d.status).replaceAll('_', ' ')}.`); setBusy('') }
  return <form onSubmit={save} className="integration-form"><section className="admin-panel"><h2>ZR Express</h2><p className="admin-muted">{settings.zrConfigured ? 'Connected' : 'Not configured'}</p><label>API Base URL<input className="admin-input" value={settings.zrBaseUrl} onChange={e => update('zrBaseUrl', e.target.value)} /></label><label>Tenant ID<input className="admin-input" value={settings.zrTenantId} onChange={e => update('zrTenantId', e.target.value)} /></label><label>API Key<input className="admin-input" type="password" value={settings.zrApiKey} onChange={e => update('zrApiKey', e.target.value)} placeholder="********" autoComplete="new-password" /></label><div className="admin-actions"><button className="admin-button" disabled={!!busy}>Save</button><button type="button" className="admin-button secondary" disabled={!!busy} onClick={() => test('zr')}>Test Connection</button></div></section><section className="admin-panel"><h2>Meta</h2><p className="admin-muted">{settings.metaConfigured ? 'Connected/configured' : 'Not configured'}</p><label>Meta Pixel ID<input className="admin-input" value={settings.metaPixelId} onChange={e => update('metaPixelId', e.target.value)} /></label><label>Meta Conversions API Access Token<input className="admin-input" type="password" value={settings.metaAccessToken} onChange={e => update('metaAccessToken', e.target.value)} placeholder="********" autoComplete="new-password" /></label><div className="admin-actions"><button className="admin-button" disabled={!!busy}>Save</button><button type="button" className="admin-button secondary" disabled={!!busy} onClick={() => test('meta')}>Test Configuration</button></div></section>{message && <p className="admin-notice" role="status">{message}</p>}</form>
}
