'use client'

import { FormEvent, useEffect, useState } from 'react'
import territories from '@/data/algeria-wilayas-communes.json'

type Props = { orderId: string; fullName: string; phone: string; wilaya: string; commune: string; address: string; quantity?: number; unitPrice?: number; totalAmount?: number; customerNotes: string; sellerNotes: string }

export function OrderDetailsForm({ orderId, fullName: initialName, phone: initialPhone, wilaya: initialWilaya, commune: initialCommune, address: initialAddress, quantity: initialQuantity = 1, unitPrice: initialUnitPrice = 0, totalAmount: initialTotalAmount = 0, customerNotes, sellerNotes: initialSellerNotes }: Props) {
  const initialWilayaRecord = territories.find(item => item.ascii === initialWilaya)
  const [values, setValues] = useState({ fullName: initialName, phone: initialPhone, wilaya: initialWilayaRecord ? String(initialWilayaRecord.code) : '', commune: initialCommune, address: initialAddress, quantity: String(initialQuantity), unitPrice: String(initialUnitPrice), totalAmount: String(initialTotalAmount), sellerNotes: initialSellerNotes })
  const [state, setState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle')
  const [message, setMessage] = useState('')
  const selectedWilaya = territories.find(item => String(item.code) === values.wilaya)
  useEffect(() => { void fetch(`/api/admin/orders?orderId=${encodeURIComponent(orderId)}`).then(response => response.ok ? response.json() : null).then(result => { const order = result?.order; if (order) setValues(current => ({ ...current, quantity: String(order.quantity), unitPrice: String(order.unit_price), totalAmount: String(order.total_amount) })) }) }, [orderId])
  function update(key: keyof typeof values, value: string) { setValues(current => { const next = { ...current, [key]: value }; if (key === 'quantity' || key === 'unitPrice') { const quantity = Number(key === 'quantity' ? value : current.quantity); const unitPrice = Number(key === 'unitPrice' ? value : current.unitPrice); next.totalAmount = Number.isFinite(quantity) && Number.isFinite(unitPrice) ? String(quantity * unitPrice) : '' } return next }); setState('idle'); setMessage('') }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState('saving'); setMessage('')
    const response = await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ orderId, fullName: values.fullName, phone: values.phone, wilayaCode: values.wilaya, commune: values.commune, address: values.address, quantity: values.quantity, unitPrice: values.unitPrice, totalAmount: values.totalAmount, sellerNotes: values.sellerNotes }) })
    const result = await response.json().catch(() => null)
    if (!response.ok) { setState('error'); setMessage(result?.error === 'customer_update_failed' ? 'Phone may already belong to another customer.' : 'Please check the order details.'); return }
    setState('saved'); setMessage('Saved')
  }
  return <form className="order-details-form admin-panel" onSubmit={save}><h2>Edit order details</h2><div className="admin-form-grid"><label>Full name<input required value={values.fullName} onChange={event => update('fullName', event.target.value)} /></label><label>Phone<input required value={values.phone} onChange={event => update('phone', event.target.value)} /></label><label>Quantity<input required type="number" min="1" max="99" step="1" value={values.quantity} onChange={event => update('quantity', event.target.value)} /></label><label>Unit price (DZD)<input required type="number" min="0" step="1" value={values.unitPrice} onChange={event => update('unitPrice', event.target.value)} /></label><label>Sale total (DZD)<input required type="number" min="0" step="1" value={values.totalAmount} onChange={event => update('totalAmount', event.target.value)} /></label><label>Wilaya<select required value={values.wilaya} onChange={event => setValues(current => ({ ...current, wilaya: event.target.value, commune: '' }))}><option value="">Select wilaya</option>{territories.map(item => <option key={item.code} value={item.code}>{item.ascii} - {item.arabic}</option>)}</select></label><label>Commune<select required disabled={!selectedWilaya} value={values.commune} onChange={event => update('commune', event.target.value)}><option value="">Select commune</option>{selectedWilaya?.communes.map(item => <option key={item.ascii} value={item.ascii}>{item.ascii} - {item.arabic}</option>)}</select></label><label className="admin-form-wide">Address<input required value={values.address} onChange={event => update('address', event.target.value)} /></label><label className="admin-form-wide">Seller note<textarea maxLength={1000} value={values.sellerNotes} onChange={event => update('sellerNotes', event.target.value)} placeholder="Internal note for the seller or team" /></label><div className="admin-form-wide admin-note-readonly"><strong>Customer note</strong><p>{customerNotes || 'No customer note.'}</p></div></div><div className="admin-actions"><button className="admin-button" disabled={state === 'saving'}>{state === 'saving' ? 'Saving...' : 'Save details'}</button>{message && <small className={state === 'error' ? 'admin-error-text' : 'admin-notice'}>{message}</small>}</div></form>
}
